
#****************************************************************************************#
# QUERIES
#****************************************************************************************#

type Query {
	bearer: String!
}

#****************************************************************************************#
