
#****************************************************************************************#
# TYPES
#****************************************************************************************#

type User {
	userName: String!
	displayName: String
	mail: String
	roles: [String]
}

type Auth {
	authorization: String!
}

#****************************************************************************************#
# QUERIES
#****************************************************************************************#

type Query {
	users: [User!]!
	currentUser: User! @authorized
}

#****************************************************************************************#
# MUTATIONS
#****************************************************************************************#

type Mutation {
	signin(userName: String!, password: String!): Auth!
	signout: String!
}

#****************************************************************************************#
